/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a38b818e-a0be-4c2d-8ab2-5b5c5b24c0fc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7CXH1Eqkm",
    "aws_user_pools_web_client_id": "tfokg6cfup01ebp9rg4ik3t0h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cm53j5mipjdh3p6f4thvv4stsu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gurvwpefire7lht4gpwfgwuwjm"
};


export default awsmobile;
